from .ui_add_row_allocation import Ui_Win_Add_Row_Allocation
from .ui_add_row_cat_expenses import Ui_Win_Add_Row_Cat_Expenses
from .ui_add_row_cat_incomes import Ui_Win_Add_Row_Cat_Incomes
from .ui_add_row_expense import Ui_Win_Add_Row_Expense
from .ui_add_row_income import Ui_Win_Add_Row_Income
from .ui_add_row import Ui_Win_Add_Row
from .ui_delete_row import Ui_Win_Delete_Row
from .ui_win_main import Ui_WinMain
