# Form implementation generated from reading ui file '\Users\mitja\Programiranje\PF2_Dev\PF2_Source\PF2_Code\ui_qt\ui_add_row_reg_income.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Win_Add_Row_Reg_Income(object):
    def setupUi(self, Win_Add_Row_Reg_Income):
        Win_Add_Row_Reg_Income.setObjectName("Win_Add_Row_Reg_Income")
        Win_Add_Row_Reg_Income.resize(603, 275)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Win_Add_Row_Reg_Income)
        self.buttonBox.setGeometry(QtCore.QRect(240, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Income)
        self.label.setGeometry(QtCore.QRect(30, 20, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Income)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Income)
        self.label_3.setGeometry(QtCore.QRect(30, 119, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_Description = QtWidgets.QLineEdit(parent=Win_Add_Row_Reg_Income)
        self.lineEdit_Description.setGeometry(QtCore.QRect(150, 120, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Description.setFont(font)
        self.lineEdit_Description.setObjectName("lineEdit_Description")
        self.Amount = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Income)
        self.Amount.setGeometry(QtCore.QRect(30, 159, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Amount.setFont(font)
        self.Amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Amount.setObjectName("Amount")
        self.lineEdit_Amount = QtWidgets.QLineEdit(parent=Win_Add_Row_Reg_Income)
        self.lineEdit_Amount.setGeometry(QtCore.QRect(150, 160, 150, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Amount.setFont(font)
        self.lineEdit_Amount.setObjectName("lineEdit_Amount")
        self.comboBoxCategory = QtWidgets.QComboBox(parent=Win_Add_Row_Reg_Income)
        self.comboBoxCategory.setGeometry(QtCore.QRect(150, 80, 241, 26))
        self.comboBoxCategory.setObjectName("comboBoxCategory")

        self.retranslateUi(Win_Add_Row_Reg_Income)
        self.buttonBox.accepted.connect(Win_Add_Row_Reg_Income.accept) # type: ignore
        self.buttonBox.rejected.connect(Win_Add_Row_Reg_Income.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Win_Add_Row_Reg_Income)

    def retranslateUi(self, Win_Add_Row_Reg_Income):
        _translate = QtCore.QCoreApplication.translate
        Win_Add_Row_Reg_Income.setWindowTitle(_translate("Win_Add_Row_Reg_Income", "Dialog"))
        self.label.setText(_translate("Win_Add_Row_Reg_Income", "New Regular Income:"))
        self.label_2.setText(_translate("Win_Add_Row_Reg_Income", "Category:"))
        self.label_3.setText(_translate("Win_Add_Row_Reg_Income", "Description:"))
        self.Amount.setText(_translate("Win_Add_Row_Reg_Income", "Amount:"))

