# Form implementation generated from reading ui file '\Users\mitja\Programiranje\Personal_Finances\PF2_Dev\PF2_Source\PF2_Code\ui_qt\ui_add_row_reg_currency.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Win_Add_Row_Reg_Currency(object):
    def setupUi(self, Win_Add_Row_Reg_Currency):
        Win_Add_Row_Reg_Currency.setObjectName("Win_Add_Row_Reg_Currency")
        Win_Add_Row_Reg_Currency.resize(495, 305)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Win_Add_Row_Reg_Currency)
        self.buttonBox.setGeometry(QtCore.QRect(130, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Currency)
        self.label.setGeometry(QtCore.QRect(30, 20, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Currency)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Currency)
        self.label_3.setGeometry(QtCore.QRect(30, 119, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_CurrName = QtWidgets.QLineEdit(parent=Win_Add_Row_Reg_Currency)
        self.lineEdit_CurrName.setGeometry(QtCore.QRect(150, 120, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_CurrName.setFont(font)
        self.lineEdit_CurrName.setObjectName("lineEdit_CurrName")
        self.Amount = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Currency)
        self.Amount.setGeometry(QtCore.QRect(30, 159, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Amount.setFont(font)
        self.Amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Amount.setObjectName("Amount")
        self.lineEdit_CurrRate = QtWidgets.QLineEdit(parent=Win_Add_Row_Reg_Currency)
        self.lineEdit_CurrRate.setGeometry(QtCore.QRect(150, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_CurrRate.setFont(font)
        self.lineEdit_CurrRate.setObjectName("lineEdit_CurrRate")
        self.lineEdit_CurrCode = QtWidgets.QLineEdit(parent=Win_Add_Row_Reg_Currency)
        self.lineEdit_CurrCode.setGeometry(QtCore.QRect(150, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_CurrCode.setFont(font)
        self.lineEdit_CurrCode.setObjectName("lineEdit_CurrCode")
        self.checkBox_IS_Crypto = QtWidgets.QCheckBox(parent=Win_Add_Row_Reg_Currency)
        self.checkBox_IS_Crypto.setGeometry(QtCore.QRect(160, 200, 31, 31))
        self.checkBox_IS_Crypto.setText("")
        self.checkBox_IS_Crypto.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_IS_Crypto.setObjectName("checkBox_IS_Crypto")
        self.Crypto = QtWidgets.QLabel(parent=Win_Add_Row_Reg_Currency)
        self.Crypto.setGeometry(QtCore.QRect(30, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Crypto.setFont(font)
        self.Crypto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Crypto.setObjectName("Crypto")

        self.retranslateUi(Win_Add_Row_Reg_Currency)
        self.buttonBox.accepted.connect(Win_Add_Row_Reg_Currency.accept) # type: ignore
        self.buttonBox.rejected.connect(Win_Add_Row_Reg_Currency.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Win_Add_Row_Reg_Currency)
        Win_Add_Row_Reg_Currency.setTabOrder(self.lineEdit_CurrCode, self.lineEdit_CurrName)
        Win_Add_Row_Reg_Currency.setTabOrder(self.lineEdit_CurrName, self.lineEdit_CurrRate)
        Win_Add_Row_Reg_Currency.setTabOrder(self.lineEdit_CurrRate, self.checkBox_IS_Crypto)

    def retranslateUi(self, Win_Add_Row_Reg_Currency):
        _translate = QtCore.QCoreApplication.translate
        Win_Add_Row_Reg_Currency.setWindowTitle(_translate("Win_Add_Row_Reg_Currency", "Dialog"))
        self.label.setText(_translate("Win_Add_Row_Reg_Currency", "New Currency:"))
        self.label_2.setText(_translate("Win_Add_Row_Reg_Currency", "Code:"))
        self.label_3.setText(_translate("Win_Add_Row_Reg_Currency", "Name:"))
        self.Amount.setText(_translate("Win_Add_Row_Reg_Currency", "Rate:"))
        self.Crypto.setText(_translate("Win_Add_Row_Reg_Currency", "Is Crypto:"))

