# Form implementation generated from reading ui file '\Users\mitja\Programiranje\PF2\ui_qt\ui_add_row_cat_incomes.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Win_Add_Row_Cat_Incomes(object):
    def setupUi(self, Win_Add_Row_Cat_Incomes):
        Win_Add_Row_Cat_Incomes.setObjectName("Win_Add_Row_Cat_Incomes")
        Win_Add_Row_Cat_Incomes.resize(603, 250)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Win_Add_Row_Cat_Incomes)
        self.buttonBox.setGeometry(QtCore.QRect(240, 190, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Win_Add_Row_Cat_Incomes)
        self.label.setGeometry(QtCore.QRect(30, 20, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Win_Add_Row_Cat_Incomes)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Win_Add_Row_Cat_Incomes)
        self.label_3.setGeometry(QtCore.QRect(30, 119, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_Category = QtWidgets.QLineEdit(parent=Win_Add_Row_Cat_Incomes)
        self.lineEdit_Category.setGeometry(QtCore.QRect(150, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Category.setFont(font)
        self.lineEdit_Category.setObjectName("lineEdit_Category")
        self.lineEdit_Description = QtWidgets.QLineEdit(parent=Win_Add_Row_Cat_Incomes)
        self.lineEdit_Description.setGeometry(QtCore.QRect(150, 120, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Description.setFont(font)
        self.lineEdit_Description.setObjectName("lineEdit_Description")

        self.retranslateUi(Win_Add_Row_Cat_Incomes)
        self.buttonBox.accepted.connect(Win_Add_Row_Cat_Incomes.accept) # type: ignore
        self.buttonBox.rejected.connect(Win_Add_Row_Cat_Incomes.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Win_Add_Row_Cat_Incomes)

    def retranslateUi(self, Win_Add_Row_Cat_Incomes):
        _translate = QtCore.QCoreApplication.translate
        Win_Add_Row_Cat_Incomes.setWindowTitle(_translate("Win_Add_Row_Cat_Incomes", "Dialog"))
        self.label.setText(_translate("Win_Add_Row_Cat_Incomes", "New Incomes Category Row:"))
        self.label_2.setText(_translate("Win_Add_Row_Cat_Incomes", "Category:"))
        self.label_3.setText(_translate("Win_Add_Row_Cat_Incomes", "Description:"))

