# Form implementation generated from reading ui file '\Users\mitja\Programiranje\PF2_Dev\PF2_Source\PF2_Code\ui_qt\ui_close_month.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ui_close_month(object):
    def setupUi(self, ui_close_month):
        ui_close_month.setObjectName("ui_close_month")
        ui_close_month.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        ui_close_month.resize(633, 104)
        self.buttonBoxCloseMonth = QtWidgets.QDialogButtonBox(parent=ui_close_month)
        self.buttonBoxCloseMonth.setGeometry(QtCore.QRect(370, 60, 241, 32))
        self.buttonBoxCloseMonth.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBoxCloseMonth.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.buttonBoxCloseMonth.setObjectName("buttonBoxCloseMonth")
        self.labelAlert = QtWidgets.QLabel(parent=ui_close_month)
        self.labelAlert.setGeometry(QtCore.QRect(30, 20, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelAlert.setFont(font)
        self.labelAlert.setObjectName("labelAlert")

        self.retranslateUi(ui_close_month)
        self.buttonBoxCloseMonth.accepted.connect(ui_close_month.accept) # type: ignore
        self.buttonBoxCloseMonth.rejected.connect(ui_close_month.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ui_close_month)

    def retranslateUi(self, ui_close_month):
        _translate = QtCore.QCoreApplication.translate
        ui_close_month.setWindowTitle(_translate("ui_close_month", "Change month\'s status?"))
        self.labelAlert.setText(_translate("ui_close_month", "Are you sure you want to change month\'s closed/opened status?"))

