# Form implementation generated from reading ui file '\Users\mitja\Programiranje\PF2_Dev\PF2_Source\PF2_Code\ui_qt\ui_dwin_alert.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DWin_Alert(object):
    def setupUi(self, DWin_Alert):
        DWin_Alert.setObjectName("DWin_Alert")
        DWin_Alert.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        DWin_Alert.resize(542, 104)
        self.buttonBoxOk = QtWidgets.QDialogButtonBox(parent=DWin_Alert)
        self.buttonBoxOk.setGeometry(QtCore.QRect(270, 60, 241, 32))
        self.buttonBoxOk.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBoxOk.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBoxOk.setObjectName("buttonBoxOk")
        self.labelAlert = QtWidgets.QLabel(parent=DWin_Alert)
        self.labelAlert.setGeometry(QtCore.QRect(30, 20, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAlert.setFont(font)
        self.labelAlert.setObjectName("labelAlert")

        self.retranslateUi(DWin_Alert)
        self.buttonBoxOk.accepted.connect(DWin_Alert.accept) # type: ignore
        self.buttonBoxOk.rejected.connect(DWin_Alert.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DWin_Alert)

    def retranslateUi(self, DWin_Alert):
        _translate = QtCore.QCoreApplication.translate
        DWin_Alert.setWindowTitle(_translate("DWin_Alert", "Alert"))
        self.labelAlert.setText(_translate("DWin_Alert", "Dummy text"))

