# Form implementation generated from reading ui file '\Users\mitja\Programiranje\PF2_Dev\PF2_Source\PF2_Code\ui_qt\ui_dwin_close_month.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DWin_Close_Month(object):
    def setupUi(self, DWin_Close_Month):
        DWin_Close_Month.setObjectName("DWin_Close_Month")
        DWin_Close_Month.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        DWin_Close_Month.resize(531, 104)
        self.buttonBoxCloseMonth = QtWidgets.QDialogButtonBox(parent=DWin_Close_Month)
        self.buttonBoxCloseMonth.setGeometry(QtCore.QRect(260, 60, 241, 32))
        self.buttonBoxCloseMonth.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBoxCloseMonth.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.buttonBoxCloseMonth.setObjectName("buttonBoxCloseMonth")
        self.labelAlert = QtWidgets.QLabel(parent=DWin_Close_Month)
        self.labelAlert.setGeometry(QtCore.QRect(30, 20, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAlert.setFont(font)
        self.labelAlert.setObjectName("labelAlert")

        self.retranslateUi(DWin_Close_Month)
        self.buttonBoxCloseMonth.accepted.connect(DWin_Close_Month.accept) # type: ignore
        self.buttonBoxCloseMonth.rejected.connect(DWin_Close_Month.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DWin_Close_Month)

    def retranslateUi(self, DWin_Close_Month):
        _translate = QtCore.QCoreApplication.translate
        DWin_Close_Month.setWindowTitle(_translate("DWin_Close_Month", "Change month\'s status?"))
        self.labelAlert.setText(_translate("DWin_Close_Month", "Are you sure you want to change month\'s closed/opened status?"))

